# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SvtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SvtUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_service', models.CharField(max_length=4)),
                ('month_of_service', models.CharField(max_length=2)),
                ('bar_code', models.CharField(max_length=10)),
                ('sn', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.SvtType')),
            ],
        ),
    ]
